# Generated by Django 6.0.5 on 2026-06-09 05:25

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extras', '0138_customfieldchoiceset_choice_colors'),
        ('virtualization', '0056_virtualmachine_render_config_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='K3sCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('nb_cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='k3s_clusters', to='virtualization.cluster')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'k3s cluster',
                'verbose_name_plural': 'k3s clusters',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='K3sNamespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=253)),
                ('comments', models.TextField(blank=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namespaces', to='netbox_k3s.k3scluster')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'k3s namespace',
                'verbose_name_plural': 'k3s namespaces',
                'ordering': ('cluster', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='K3sPod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=253)),
                ('image', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(default='Unknown', max_length=50)),
                ('node', models.CharField(blank=True, max_length=253)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pods', to='netbox_k3s.k3snamespace')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'k3s pod',
                'verbose_name_plural': 'k3s pods',
                'ordering': ('namespace', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='K3sService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=253)),
                ('type', models.CharField(default='ClusterIP', max_length=50)),
                ('cluster_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ports', models.CharField(blank=True, max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='netbox_k3s.k3snamespace')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'k3s service',
                'verbose_name_plural': 'k3s services',
                'ordering': ('namespace', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='k3snamespace',
            constraint=models.UniqueConstraint(fields=('cluster', 'name'), name='netbox_k3s_namespace_unique_cluster_name'),
        ),
        migrations.AddConstraint(
            model_name='k3spod',
            constraint=models.UniqueConstraint(fields=('namespace', 'name'), name='netbox_k3s_pod_unique_namespace_name'),
        ),
        migrations.AddConstraint(
            model_name='k3sservice',
            constraint=models.UniqueConstraint(fields=('namespace', 'name'), name='netbox_k3s_service_unique_namespace_name'),
        ),
    ]
